Feature/komarch 14 tags
SlovakNationalGallery/komarch.sk pull request #11
Opened 2020-12-15 14:38 UTC by yanchith

Add crud for tags and relationships between tags and posts.

2020-12-16 15:16 UTC, igor-kamil requested changes
just a very tiny hints

2020-12-16 15:16 UTC, igor-kamil commented on app/Http/Requests/TagRequest.php
> +            // 'name' => 'required|min:5|max:255'
I am up for defining some rules. At least name is realy required
```suggestion
             'name' => 'required|min:2|max:255'
```

2020-12-16 15:16 UTC, igor-kamil commented on app/Models/Post.php
> -    public $with = ['tags'];
just asking - why did you remove it? this makes eager loading. saving amount of db queries.

2020-12-16 15:16 UTC, igor-kamil commented on resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
> +<li class='nav-item'><a class='nav-link' href='{{ backpack_url('tag') }}'><i class='nav-icon la la-question'></i> Tags</a></li>
what about to choose nicer icon instead of `la-question` ? ;)

2020-12-17 15:51 UTC, yanchith commented on app/Models/Post.php
> -    public $with = ['tags'];
Probably just my misunderstanding of things! I thought that when you define it with a method, it does the same, but now I looked at the docs and see this is something else. I'll put it back.

2020-12-17 16:39 UTC, yanchith commented
@igor-kamil All done, I believe 🙂

2020-12-18 08:04 UTC, igor-kamil approved these changes
🌟

2020-12-18 08:09 UTC, merged