Komarch 128 works admin
SlovakNationalGallery/komarch.sk pull request #63
Opened 2021-06-11 14:38 UTC by igor-kamil

works:
![Screenshot 2021-06-11 at 16 36 33](https://user-images.githubusercontent.com/2682941/121703626-53eec800-cad3-11eb-8d6a-3fd3149f19a1.png)

awards:
![Screenshot 2021-06-11 at 16 36 43](https://user-images.githubusercontent.com/2682941/121703631-551ff500-cad3-11eb-9c17-3003000417ca.png)

2021-06-11 15:43 UTC, eronisko requested changes
This brings quite a bit of boilerplate. Can you please clean it up?

* most `setup` methods in CrudControllers can be removed
* the new `Request` classes can probably be deleted entirely

2021-06-11 15:43 UTC, eronisko commented on app/Http/Controllers/Admin/AwardCrudController.php
> +        $this->crud->denyAccess('create');
Wouldn't it be enough to remove the `CreateOperation`, `UpdateOperation` and` DeleteOperation` above?

We could also get rid of all the boilerplace below

2021-06-11 15:43 UTC, eronisko commented on app/Models/Award.php
> +        return $this->belongsToMany(Work::class);
Import for `Work` is probably missing

2021-06-11 15:43 UTC, eronisko commented on app/Http/Requests/AwardRequest.php
> +<?php
I'd delete this whole file (it does nothing IMHO)

2021-06-13 20:13 UTC, igor-kamil commented on app/Models/Award.php
> +        return $this->belongsToMany(Work::class);
what do you mean exactly? do use full namespace / or define in beginning? since it's within the same namespace... it is not necessary and it works. or you mean something else?

2021-06-13 20:17 UTC, igor-kamil commented on app/Http/Controllers/Admin/AwardCrudController.php
> +        $this->crud->denyAccess('create');
no. this is necessary to hide also action buttons

2021-06-13 20:19 UTC, igor-kamil commented
@eronisko better now?

2021-06-15 10:07 UTC, eronisko approved these changes

2021-06-15 10:07 UTC, eronisko commented on app/Models/Award.php
> +        return $this->belongsToMany(Work::class);
Ah, OK. I always import but as long as it works, then fine.

2021-06-15 10:07 UTC, eronisko commented on app/Http/Controllers/Admin/AwardCrudController.php
> +    use \Backpack\CRUD\app\Http\Controllers\Operations\DeleteOperation;
Can these be deleted?
```suggestion
```

2021-06-15 10:07 UTC, eronisko commented on app/Http/Controllers/Admin/WorkCrudController.php
> +    use \Backpack\CRUD\app\Http\Controllers\Operations\DeleteOperation;
```suggestion
```

2021-06-15 12:06 UTC, igor-kamil commented on app/Http/Controllers/Admin/AwardCrudController.php
> +    use \Backpack\CRUD\app\Http\Controllers\Operations\DeleteOperation;
yes! it does 😉  👓

2021-06-15 12:09 UTC, merged